sudo: required
dist: trusty
language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
before_install:
  - sudo apt-get install -y openjdk-8-jdk
script:
  - chmod +x run-scanner.sh
  - ./run-scanner.sh
